title: ROBOCOPY GUI Manager
description: Professional Windows ROBOCOPY GUI Manager - Standalone executable for easy file operations
theme: jekyll-theme-cayman
show_downloads: true
github:
  is_project_page: true
  repository_name: sagarsorathiya/ROBOCOPY-GUI-Manager
  repository_url: https://github.com/sagarsorathiya/ROBOCOPY-GUI-Manager
  owner_name: Sagar Sorathiya
  owner_url: https://github.com/sagarsorathiya
